# Use the official Python 3.12 image from the Docker Hub
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy FastAPI source code into the container
#COPY fastAPI/ /app
COPY . /app

# Install dependencies
#RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port FastAPI runs on
EXPOSE 8000

# Run FastAPI using Uvicorn
CMD ["uvicorn", "fastAPI.api:app", "--host", "0.0.0.0", "--port", "8000"]